language: node_js
node_js:
  - "node"
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disbale-gpu --remote-debugging-port=9876 http://localhost &
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
install:
  - npm install
script: 
  - npm test