language: node_js
node_js:
  - "node"
dist: trusty
addons:
  apt:
    packages:
      - google-chrome-stable
before_install:
  - google-chrome-stable --headless --no-sandbox --disbale-gpu --remote-debugging-port=9222 http://localhost &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
install:
  - npm install
script: 
  - npm test